language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-webenv' ]; then cd .. && eval "mv $currentfolder generator-webenv" && cd generator-webenv; fi

